### ISSUE TITLE
Docker Build Fails

### ISSUE THREAD

**Issue by sclel016** [ulx3s/quick-start#1]
Hi,

I tried building from source using the Docker instructions provided in the Readme. The build is failing during `make build`, I've opened an issue with the docker repository [here](https://github.com/alpin3/ulx3s/issues/2#issue-715160000). I'm opening an issue here in case others following the instructions experience the same problem.

Stew

**Comment by goran-mahovlic** [comment]
Thank you, @kost will check what is happening with building ...

**Comment by kost** [comment]
Thanks on report. Fixed. Let me know if it works for you now!

**Comment by kost** [comment]
https://github.com/alpin3/ulx3s

**Comment by sclel016** [comment]
Confirmed the fix works, thanks!
